// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANM9C44hKOoJyd-RPasXVaXw2ah5e2tyQ',
    appId: '1:66260405592:web:a843dd4e27651d9305a92d',
    messagingSenderId: '66260405592',
    projectId: 'fir-sample-c2c6c',
    authDomain: 'fir-sample-c2c6c.firebaseapp.com',
    storageBucket: 'fir-sample-c2c6c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA30xF5oXh39y0pZy6LOzNlJdlnwN762XE',
    appId: '1:66260405592:android:8b7a321bccb3362705a92d',
    messagingSenderId: '66260405592',
    projectId: 'fir-sample-c2c6c',
    storageBucket: 'fir-sample-c2c6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1hn0iUpWqpqtOVLAiA9rgz1tSGpdJhfI',
    appId: '1:66260405592:ios:2af7b4a68b933c2d05a92d',
    messagingSenderId: '66260405592',
    projectId: 'fir-sample-c2c6c',
    storageBucket: 'fir-sample-c2c6c.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSampleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANM9C44hKOoJyd-RPasXVaXw2ah5e2tyQ',
    appId: '1:66260405592:web:66aa56afca83184505a92d',
    messagingSenderId: '66260405592',
    projectId: 'fir-sample-c2c6c',
    authDomain: 'fir-sample-c2c6c.firebaseapp.com',
    storageBucket: 'fir-sample-c2c6c.firebasestorage.app',
  );
}
